apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nemo-core.controller-servicename" . }}
  labels:
    app.kubernetes.io/component: nemo-core-controller
    {{- include "nemo-core.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.controller.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1 # Controller always runs with a single replica
  selector:
    matchLabels:
      app.kubernetes.io/component: nemo-core-controller
      {{- include "nemo-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.controller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.global.platformConfigmapName }}
        checksum/configmap: {{ include (print $.Template.BasePath "/platform-configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        app.kubernetes.io/component: nemo-core-controller
        {{- include "nemo-core.labels" . | nindent 8 }}
        {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        {{ include "nemo-common.imagepullsecrets" . | nindent 8 | trim }}
      serviceAccountName: {{ include "nemo-core.controllerServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-controller
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: {{ include "nemo-common.mainimage" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--start-controllers"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.controller.env }}
            {{ toYaml .Values.controller.env | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.config.jobs.port | default 8000 }}
              protocol: TCP
          {{- with .Values.controller.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath:  /etc/nmp/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "nemo-common.platform-configmap-name" . }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
