{{- if and .Values.config.models.database.password (not .Values.config.models.database.passwordExistingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemo-core.fullname" . }}-models-db-secret
  labels:
    app.kubernetes.io/component: nemo-core-models-db
    {{- include "nemo-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.config.models.database.password | quote }}
{{- end }}

