apiVersion: v2
appVersion: "25.12"
dependencies:
- name: nemo-common
  repository: file://../../../library/
  version: '>=0.1.0-0'
description: A Helm chart to install NeMo Studio UI
name: nemo-studio-ui
type: application
version: 25.12.0
