
{{- if (not .Values.classify.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemo-safe-synthesizer.secret-name" .}}
type: Opaque
data:
  NEMO_MICROSERVICES_SAFE_SYNTHESIZER_CLASSIFY_LLM_API_KEY: {{ .Values.classify.apiKey | b64enc | quote }}
{{- end }}
