apiVersion: v1
kind: Service
metadata:
  name: {{ include "nemo-core.api-servicename" . }}
  labels:
    app.kubernetes.io/component: nemo-core-api
    {{- include "nemo-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: nemo-core-api
    {{- include "nemo-core.selectorLabels" . | nindent 4 }}
