{{- if .Values.config.models.datastore_secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.models.datastore_secret.name }}
  labels:
    {{- include "nemo-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  HF_TOKEN: ""
{{- end }}

