{{- if .Values.logcollector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nemo-core.logcollectorServiceAccountName" . }}
  labels:
    {{- include "nemo-core.labels" . | nindent 4 }}
  {{- with .Values.logcollector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.logcollector.serviceAccount.automount }}
{{- end }}
