apiVersion: v2
appVersion: "25.12"
dependencies:
- name: nemo-common
  repository: file://../../../library/
  version: '>=0.1.0-0'
description: A Helm chart for NeMo Safe Synthesizer service
home: https://nvidia.com
maintainers:
- name: NVIDIA, Inc.
  url: https://www.nvidia.com
name: nemo-safe-synthesizer
type: application
version: 25.12.0
