apiVersion: v2
appVersion: "25.11"
dependencies:
- name: nemo-operator-crds
  repository: file://charts/nemo-operator-crds
  version: 0.1.2
- name: nemo-common
  repository: file://../../../library/
  version: '>=0.1.0-0'
description: NeMo Operator Microservice Helm Chart
name: nemo-operator
type: application
version: 25.11.0
