#
# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}

{{- include "oracle-db-labels" . | indent 2}}
spec:
  serviceName: {{ template "fullname" . }}-headless
  replicas: {{ default 1 .Values.replicas }}
  selector:
    matchLabels:
      {{- include "oracle-db-fullname.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oracle-db-fullname.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "oracle-db.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- if .Values.imagePullSecrets}}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      securityContext:
        runAsUser: 54321
        fsGroup: 54321
      {{- if or .Values.availabilityDomain .Values.nodeLabels}}
      nodeSelector:
      {{- range $key, $value := .Values.nodeLabels }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- if .Values.availabilityDomain }}
        failure-domain.beta.kubernetes.io/zone: "{{ .Values.availabilityDomain }}"
      {{- end }}
      {{- end }}
      containers:
        - name: oracle-db
          image: {{ .Values.image }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.imagePullPolicy | quote }}
          {{- if .Values.preStopHook }}
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "/bin/echo -en 'shutdown abort;\n' | env ORACLE_SID=${ORACLE_SID^^} sqlplus -S / as sysdba" ]
          {{- end }}
          ports:
            - containerPort: 1521
              name: listener
            - containerPort: 5500
              name: em-express
          readinessProbe:
            exec:
              command: [ "/bin/sh", "-c", "if [ -f $ORACLE_BASE/checkDBLockStatus.sh ]; then $ORACLE_BASE/checkDBLockStatus.sh ; else $ORACLE_BASE/checkDBStatus.sh; fi " ]
            initialDelaySeconds: 20
            periodSeconds: 40
            timeoutSeconds: 20
          {{- if .Values.persistence.enable }}
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: datamount
          {{- end }}
          {{- include "oracle-db-env" . | indent 10 }}
  {{- if .Values.persistence.enable }}
  volumeClaimTemplates:
  - metadata:
      name: datamount
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 20Gi
      storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}

